# Generated by Django 4.2.4 on 2023-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
