# Generated by Django 4.2.4 on 2023-08-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_to_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
